### import mxnet as mx

so that we can use components from mxnet with mx

In [3]:
import mxnet as mx

### Create NDArray variables

You can define NDArray variables which are full of "ones" with `mx.nd.ones(<shape>)`,
and NDArray variables which are full of "zeros" with `mx.nd.zeros(<shape>)`.

Basic mathematical operators can be used directly with these NDArray variables.

To get all the values in the NDArray, you can use `asnumpy()` function of NDArray

In [4]:
a = mx.nd.ones((3,4))
b = mx.nd.zeros((3,4))

c = a + b

c.asnumpy()

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]], dtype=float32)

###  Create random NDArray


`mx.nd.empty(<shape>)` can be used to create NDArray full of random numbers:

In [5]:
random_NDArray = mx.nd.empty((5,5))

random_NDArray.asnumpy()

array([[  0.00000000e+00,   2.52435490e-29,   0.00000000e+00,
          2.52435490e-29,   1.40129846e-44],
       [  0.00000000e+00,   8.40779079e-45,   0.00000000e+00,
          0.00000000e+00,   1.26116862e-44],
       [  1.26116862e-44,   1.26116862e-44,   1.26116862e-44,
          1.26116862e-44,   1.26116862e-44],
       [  1.26116862e-44,   0.00000000e+00,   0.00000000e+00,
          1.68155816e-44,   0.00000000e+00],
       [  0.00000000e+00,   2.10194770e-44,   0.00000000e+00,
          0.00000000e+00,   2.52233724e-44]], dtype=float32)

### Create NDArray full of a number

`mx.nd.full(<shape>, <number>)` can be used to create NDArray full of a number you assign with the parameter "number"


In [6]:
eight_NDArray = mx.nd.full((3,3), 8)

eight_NDArray.asnumpy()

array([[ 8.,  8.,  8.],
       [ 8.,  8.,  8.],
       [ 8.,  8.,  8.]], dtype=float32)